---
version: '3.8'

services:
  sales_api:
    container_name: sales_api
    image: node:18.12.1-alpine
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c 'yarn install && yarn build && yarn dev'
    ports:
      - "4500:4500"
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENVIRONMENT: ${APP_ENVIRONMENT}
      APP_PORT: ${APP_PORT}
      DB_POSTGRES_HOST: ${DB_POSTGRES_HOST}
      DB_POSTGRES_PORT: ${DB_POSTGRES_PORT}
      DB_POSTGRES_NAME: ${DB_POSTGRES_NAME}
      DB_POSTGRES_USER: ${DB_POSTGRES_USER}
      DB_POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - sharedNetwork

  postgres:
    container_name: sales_database
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_POSTGRES_NAME}
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
    ports:
      - "5439:5432"
    networks:
      - sharedNetwork

networks:
  sharedNetwork:
    name: shared-network